[project]
name = "pomodoro-timer"
version = "0.1.0"
description = "A simple pomodoro timer"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.3.0",
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src"
]
